"""Ticket model — the internal workflow unit for a security issue.

See `docs/data-model.md` (Ticket, TicketStatus Enum, TicketPriority Enum),
`docs/features/tickets/tickets.md` (SNTL-{n} Format, Confidential Tickets,
Coordinated Release Date), `docs/features/tickets/ticket-priority.md`
(Persistence and Effective Priority), and
`docs/features/tickets/cvss-scoring.md` (Unified CVE Severity) for the full
specification. This module implements only the persistence root; ticket
identifier resolution, lifecycle, duplicate locking, priority refresh, and
Coordinated Release Date rules belong to the ticket services.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Identity,
    Index,
    Integer,
    String,
    false,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.enums import TicketStatus
from app.database import Base

if TYPE_CHECKING:
    from app.models.cve import CVE
    from app.models.ticket_access_grant import TicketAccessGrant
    from app.models.ticket_audit_event import TicketAuditEvent
    from app.models.ticket_package import TicketPackage
    from app.models.ticket_reference import TicketReference
    from app.models.user import User


class Ticket(Base):
    """A security-issue workflow unit, optionally associated with one CVE.

    `sequence_id` is assigned by PostgreSQL (`GENERATED BY DEFAULT AS
    IDENTITY`) and exposed as `SNTL-{n}`; its immutability is a service
    contract. `status` is Category A and protected by
    `chk_ticket_status_valid`. `severity_manual` (PascalCase `Severity`),
    `priority_auto`, and `priority_override` (`TicketPriority`) are Category
    B columns validated by the writing service; `NULL` in each means "not
    set" and is distinct from every label. The effective priority
    `COALESCE(priority_override, priority_auto)` is derived at read time and
    not stored. Tickets are never deleted (`docs/data-model.md`, Ticket,
    Deletion policy).
    """

    __tablename__ = "ticket"
    __table_args__ = (
        CheckConstraint(
            f"status IN ({', '.join(repr(e.value) for e in TicketStatus)})",
            name="chk_ticket_status_valid",
        ),
        CheckConstraint(
            "(status = 'Duplicated' AND duplicate_of_id IS NOT NULL) "
            "OR (status != 'Duplicated' AND duplicate_of_id IS NULL)",
            name="chk_ticket_duplicate_status_coherence",
        ),
        CheckConstraint(
            "duplicate_of_id <> id",
            name="chk_ticket_no_self_duplicate",
        ),
        CheckConstraint(
            "severity_manual IS NULL OR cve_id IS NULL",
            name="chk_ticket_severity_manual_cve_exclusive",
        ),
        Index(
            "ix_ticket_duplicate_of_id",
            "duplicate_of_id",
            postgresql_where=text("duplicate_of_id IS NOT NULL"),
        ),
        # Non-partial, so it also serves `assignee=none` (docs/data-model.md,
        # Ticket, Indexes).
        Index("ix_ticket_assignee_id", "assignee_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid7,
        server_default=text("uuidv7()"),
    )
    sequence_id: Mapped[int] = mapped_column(
        Integer, Identity(), unique=True, nullable=False
    )
    cve_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cve.id"), unique=True, nullable=True
    )
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=TicketStatus.NEW.value,
        server_default=TicketStatus.NEW.value,
    )
    severity_manual: Mapped[str | None] = mapped_column(String(20), nullable=True)
    priority_auto: Mapped[str | None] = mapped_column(String(10), nullable=True)
    priority_override: Mapped[str | None] = mapped_column(String(10), nullable=True)
    assignee_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("user.id"), nullable=True
    )
    duplicate_of_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("ticket.id"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
    is_confidential: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=false()
    )
    coordinated_release_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    cve: Mapped[CVE | None] = relationship(
        "CVE", back_populates="ticket", foreign_keys=[cve_id]
    )
    assignee: Mapped[User | None] = relationship(
        "User", back_populates="assigned_tickets", foreign_keys=[assignee_id]
    )
    duplicate_of: Mapped[Ticket | None] = relationship(
        "Ticket",
        remote_side=[id],
        back_populates="duplicates",
        foreign_keys=[duplicate_of_id],
    )
    # passive_deletes="all": Tickets are never deleted (docs/data-model.md,
    # Ticket, Deletion policy). Without this flag SQLAlchemy would null each
    # dependent's `duplicate_of_id` before deleting the target, which would
    # either silently rewrite duplicate links or surface as an unrelated
    # CHECK violation. The database FK must reject the delete instead.
    duplicates: Mapped[list[Ticket]] = relationship(
        "Ticket",
        back_populates="duplicate_of",
        foreign_keys=[duplicate_of_id],
        passive_deletes="all",
    )
    # passive_deletes="all": Tickets are never deleted. Without it SQLAlchemy
    # would try to null the NOT NULL `ticket_id` of loaded audit events and
    # grants before deleting the Ticket; the database FKs (`NO ACTION` for
    # audit events, `RESTRICT` for grants) must reject the delete instead.
    audit_events: Mapped[list[TicketAuditEvent]] = relationship(
        "TicketAuditEvent",
        back_populates="ticket",
        passive_deletes="all",
    )
    access_grants: Mapped[list[TicketAccessGrant]] = relationship(
        "TicketAccessGrant",
        back_populates="ticket",
        passive_deletes="all",
    )
    # passive_deletes="all": Tickets are never deleted and the package tree
    # is soft-deleted. Without it SQLAlchemy would try to null the NOT NULL
    # `ticket_id` of loaded packages before deleting the Ticket; the database
    # FK (default NO ACTION) must reject the delete instead.
    packages: Mapped[list[TicketPackage]] = relationship(
        "TicketPackage",
        back_populates="ticket",
        passive_deletes="all",
    )
    # References are owned children (`FK(ticket.id) ON DELETE CASCADE`).
    # `passive_deletes=True` leaves unloaded children to that database
    # cascade; the ORM cascade deletes children already loaded in the
    # session, so it never attempts to null their NOT NULL foreign key.
    references: Mapped[list[TicketReference]] = relationship(
        "TicketReference",
        back_populates="ticket",
        cascade="all, delete",
        passive_deletes=True,
    )
